print("*******print these followings line*******")
print("this is \\\\ double backslash")
print("/\\/\\/\\/\\/\\/\\/\\ this is mountain")
print("he is \t awesome(use escape sequence instead of manual space)")
print("\\\"\\n\\\'(print this as an output)")
print("this is 4 backslash \\\\\\\\")
print("\\\"\\\'")
print("Sanjay \\n Kumar")
print("Sanjay \n Kumar")
print("Sanjay \\t Kumar")
print("Sanjay \t Kumar")